### ISSUE TITLE
Hardware choices and scheme of the project

### ISSUE THREAD

**Issue by nebcio** [copilot-app/copilot-obd#3]
- [x] read about LoRa / LoRaWAN and describe & draw scheme of the infrastructure
- [x] find 2-3 store links
- [x] scheme in uml

**Comment by nebcio** [comment]
Wszystkie standard europejski: 868 MHz - 915 MHz
[46,35 + dostawa](https://techfun.sk/pl/produkt/komunikacny-modul-sx1276-lora-433-868-915-mhz/?attribute_pa_variant=433mhz-rfm96w&lang=pl&currency=PLN)
[47.53 + dostawa](https://www.tme.eu/pl/details/rfm95w-868s2/moduly-rf/hope-microelectronics/rfm95w-868s2r/?brutto=1&currency=PLN)
[40 + dostawa, miejsce na antenę](https://sklep.inncraft.pl/modul-radiowy-e220-900t22d-lora-868mhz?srsltid=AfAwrE4uUV3DkXUfKJZ8HI9g1tdLZPFiyO6YKg8R9Ye05zrKwOjHrGPqo3s)
[38.79 + dostawa, ale trochę podejrzane](https://www.mouser.pl/ProductDetail/Olimex-Ltd/LoRa868?qs=Rp5uXu7WBW%252B5bx37svhu7w%3D%3D)

nie wiem co to ale są teżtakie rzeczy z tą samą częstotliwością tyko opisane jako Am/FM a nie lora
https://www.soselectronic.com/pl/products/hoperf/rfm300w-868s2-254213?vat=1
https://erli.pl/produkt/modul-radiowy-rf-868-mhz-cc1101-nadajnik-odbiornik-z-antena,73562687

**Comment by nebcio** [comment]
kupowanie elementów osobno(nie wliczając dostawy) wychodzi powiedzmy kolo 30 zł taniej niż w tym linku poniżej)
[zestaw esp32 + lora + oled 0.96"](https://nettigo.pl/products/modul-rozwojowy-heltec-wifi-lora-32-v2-868mhz-esp32-lora-oled-0-96)

**Comment by yksen** [comment]
[GPS module](https://nettigo.pl/products/modul-gps-z-antena-aktywna-neo6mv2)

**Comment by yksen** [comment]
[GPS module](https://nettigo.pl/products/modul-gps-z-antena-aktywna-neo6mv2)

**Comment by nebcio** [comment]
![image](https://user-images.githubusercontent.com/73241633/231878059-5fb76f34-b58a-45bc-a40f-d9b01c42718d.png)

**Comment by nebcio** [comment]
![image](https://user-images.githubusercontent.com/73241633/232209835-051626ec-5e16-46bc-a172-abcd992fb201.png)

**Comment by nebcio** [comment]
@startuml

skin rose

title Copilot-OBD Scheme
left to right direction
 
package "Vehicle" #B0B0B0 {
    component #EEEEEE [OBD II\nInterface] as OBDII
}

node "Electronics" #D9D9D9 {
    #90D0FF [Bluetooth Adapter OBDII] as ELM327
    component ESP32 #99D9D9 {
      #EEEEEE [Bluetooth] as BT
      #B0B0B0 [WiFi] as WF
    }
    #40FF40 [GPS Module] as GM
    #40FF40 [LoRa Tranceiver] as LT  
} 

cloud GPS {
}

cloud LoRa {
}

package "Phone" #B0B0B0 {
    component #EEEEEE [CopilotApp\nInterface] as App
}

OBDII --> ELM327
ELM327 ..> BT
BT <..> App
LT <--> ESP32
GM <--> ESP32
LT ..> LoRa
GM <.left.> GPS
LoRa ..> App

@enduml

**Comment by nebcio** [comment]
```plantuml
title Copilot-OBD Scheme
left to right direction
 
package "Vehicle" #B0B0B0 {
    component #EEEEEE [OBD II\nInterface] as OBDII
}

node "Electronics" #D9D9D9 {
    #90D0FF [Bluetooth Adapter OBDII] as ELM327
    component ESP32 #99D9D9 {
      #EEEEEE [Bluetooth] as BT
      #B0B0B0 [WiFi] as WF
    }
    #40FF40 [GPS Module] as GM
    #40FF40 [LoRa Tranceiver] as LT  
} 

cloud GPS {
}

cloud LoRa {
}

package "Phone" #B0B0B0 {
    component #EEEEEE [CopilotApp\nInterface] as App
}

OBDII --> ELM327
ELM327 ..> BT
BT <..> App
LT <--> ESP32
GM <--> ESP32
LT ..> LoRa
GM <.left.> GPS
LoRa ..> App

```

**Comment by yksen** [comment]
Updated version
```plantuml
@startuml
skin rose
skinparam ArrowColor #000000
skinparam BackgroundColor #D9D9D9
skinparam CloudBackgroundColor #80D9FF
skinparam CloudBorderColor #000000
skinparam ComponentBackgroundColor #D9D9D9
skinparam ComponentBorderColor #000000
skinparam NodeBackgroundColor #5FCFFF
skinparam NodeBorderColor #000000
skinparam PackageBackgroundColor #FFFFFF
skinparam Linetype ortho

title Copilot OBD Scheme

Cloud "LoRaWAN" {
}

Cloud "GPS" {
}

Package "Vehicle" {
    Node "OBD-II Interface" as OBDII
}

Package "Phone" {
    Node "Copilot App Interface" as App
}

Package "Electronics" {
    Node "GPS Module" as GPSModule
    Node "LoRa Transceiver" as LoRaModule
    Node "OBD-II Bluetooth Adapter" as ELM327
    Node "ESP32" #D9D9D9 {
        Node "Bluetooth"
        Node "WiFi"
    }
}

OBDII -down-> ELM327
ELM327 .down.> Bluetooth
Bluetooth <.down.> App
LoRaModule .down.> LoRaWAN
GPSModule .up.> GPS
LoRaWAN <.left.> App
GPSModule <-down-> ESP32
LoRaModule <-left-> ESP32
@enduml
```
